Upgraded to PostCSS 6 and added the custom parser option
arccoza/metalsmith-with-postcss pull request #1
Opened 2017-08-16 14:02 UTC by 5310

I needed to use the SugarSS syntax with PostCSS, and noticed that the plugin didn't support the PostCSS parser options yet. 

I just upgraded the package, and added the option in with a working default. I hope this is acceptable.

2017-08-16 14:04 UTC, 5310 commented
I wasn't sure if an expanded example was necessary so I didn't add one beyond the doc.

For reference, I'm using the new option like this:
```js
const Metalsmith = require('metalsmith')
const json = require('jsonfile').readFileSync

new Metalsmith(__dirname)
  .destination('./dist')
  .use(require('metalsmith-babel')(json('.babelrc')))
  .use(require('metalsmith-with-postcss')(
    Object.assign({}, json('.postcssrc'), {
      pattern: ["**/*.sss"],
      parser: require('sugarss')
    })
  ))
  .use(require('metalsmith-rename')([[/\.sss$/, '.css']]))
  .use(require('metalsmith-with-postcss')(
    Object.assign({}, json('.postcssrc'), {
      pattern: ["**/*.css"]
    })
  ))
  .build(console.log)
```

2017-08-16 21:47 UTC, arccoza commented
Thanks for this pull, the expanded example is a good idea, I will do a complete review and get back to you.

2017-08-16 22:04 UTC, arccoza requested changes
This looks good, just a few small tweaks, before merging. To update the pull, just push additional changes to the same branch (`master`) in your fork.

2017-08-16 22:04 UTC, arccoza commented on package.json
> +  "version": "1.0.1",
Version should be `1.1.0` according to semver rules.

2017-08-16 22:04 UTC, arccoza commented on index.js
> +    parser: undefined,
If you're going to add the parser option, perhaps you should add the `syntax` and `stringifier` options as well.

2017-08-16 22:04 UTC, arccoza commented on index.js
> +        parser: options.parser,
`syntax` and `stringifier` options too.

2017-08-16 22:04 UTC, arccoza commented on package.json
> +    "postcss": "^6.0.9"
A broader version range, `6.x`, so the plugin postcss dependency remains up to date.

2017-08-16 22:04 UTC, arccoza commented on CHANGELOG.md
> +- `parser` options.
`syntax` and `stringifier` options too.

2017-08-16 22:04 UTC, arccoza commented on README.md
> +  - `parser`
Add the expanded code example.

2017-08-17 04:48 UTC, 5310 commented on package.json
> +  "version": "1.0.1",
Oops!

2017-08-17 04:48 UTC, 5310 commented on package.json
> +    "postcss": "^6.0.9"
What about Minimatch though?

2017-08-17 04:48 UTC, 5310 commented on index.js
> +    parser: undefined,
Should've. Will do.

2017-08-17 04:59 UTC, arccoza commented on package.json
> +    "postcss": "^6.0.9"
Minimatch is fine, it's still on 3.0.4, and isn't the important dep. I actually wanted to replace it with [micromatch](https://github.com/micromatch/micromatch) sometime.

2017-08-17 05:08 UTC, arccoza commented on CHANGELOG.md
> +- `parser` options.
Don't forget to change the version here as well (1.1.0).

2017-08-17 05:24 UTC, arccoza commented on package.json
> +    "postcss": "^6.x"
It should be just `6.x` without the `^`.

2017-08-17 05:26 UTC, arccoza commented on package.json
> +    "postcss": "^6.x"
Useful [semver tester](https://semver.npmjs.com/).

2017-08-17 05:31 UTC, 5310 commented on package.json
> +    "postcss": "^6.x"
That _is_ very useful. Bookmarked!

2017-08-17 05:32 UTC, 5310 commented
Made the changes. Does the placement of the expanded example work?

2017-08-17 05:40 UTC, 5310 commented
Newer errors fixed, hopefully.

2017-08-17 05:40 UTC, arccoza commented on README.md
> +  - `parser`
You've got parser twice here in the docs, and no `syntax` option.

2017-08-17 05:49 UTC, 5310 commented on README.md
> +  - `parser`
Embarrassing. Fixed.

2017-08-17 05:56 UTC, 5310 reviewed
Sorry for all these documentation mistakes. I went over them again and I think they're all covered now.

2017-08-17 06:04 UTC, arccoza commented on package.json
> +    "postcss": "^6.x"
The dep should be simply: `"postcss": "6.x"`

2017-08-17 06:07 UTC, arccoza approved these changes

2017-08-17 06:08 UTC, arccoza commented
No worries, and thanks for contributing, I'm going to merge this now.

2017-08-17 06:15 UTC, merged

2017-08-17 06:16 UTC, 5310 commented
Thanks for the merge! Updating my project to the original NPM module again :D

2017-08-17 06:25 UTC, arccoza commented
I've just published the update to NPM, so you should be good.